{
 "title": "Container & Node性能监控",
 "description": "中文 docker 容器 cadvisor 和主机指标面板",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "addr", "label": "Node_IP", "query": { "query": "label_values(addr)" } },
   {
    "name": "name",
    "label": "容器Name",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{addr=\"$addr\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "主机指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "1m 负载",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{addr=~\"$addr\"}"
    }
   ]
  },
  {
   "title": "5m 负载",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{addr=~\"$addr\"}"
    }
   ]
  },
  {
   "title": "系统正常运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{addr=~\"$addr\"}"
    }
   ]
  },
  {
   "title": "正在运行的容器数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{addr=\"$addr\", name=~\".+\"})"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{addr=\"$addr\", mode='idle'}[1m])) by (server) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{addr=~\"$addr\"} - node_memory_MemAvailable_bytes{addr=~\"$addr\"}) / node_memory_MemTotal_bytes{addr=~\"$addr\"} * 100"
    }
   ]
  },
  {
   "title": "swap 使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{addr=\"$addr\"} - node_memory_SwapFree_bytes{addr=\"$addr\"}) / node_memory_SwapTotal_bytes{addr=\"$addr\"} * 100"
    }
   ]
  },
  {
   "title": "15m 负载",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{addr=~\"$addr\"}"
    }
   ]
  },
  {
   "title": "主机 CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{addr=\"$addr\", mode='idle'}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "总使用率"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"user\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "user"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"system\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "system"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"steal\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "steal"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"softirq\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "softirq"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"nice\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "nice"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"irq\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "irq"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"iowait\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "iowait"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{addr=~\"$addr\", mode=\"idle\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "主机内存使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{addr=~\"$addr\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{addr=~\"$addr\"} - node_memory_MemAvailable_bytes{addr=~\"$addr\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{addr=~\"$addr\"}",
     "legendFormat": "Availavle"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{addr=\"$addr\", device=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{addr=\"$addr\", device=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_Transmit"
    }
   ]
  },
  {
   "title": "磁盘每秒 I/O 容量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{addr=~\"$addr\"}[$__rate_interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{addr=~\"$addr\"}[$__rate_interval])",
     "legendFormat": "{{device}}_written"
    }
   ]
  },
  {
   "title": "磁盘信息",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{addr=~\"$addr\"}"
    },
    {
     "expr": "node_filesystem_free_bytes{addr=~\"$addr\"}"
    },
    {
     "expr": "(node_filesystem_size_bytes{addr=~\"$addr\"} - node_filesystem_free_bytes{addr=~\"$addr\"})"
    },
    {
     "expr": "(node_filesystem_size_bytes{addr=~\"$addr\"} - node_filesystem_free_bytes{addr=~\"$addr\"}) / (node_filesystem_size_bytes{addr=~\"$addr\"})"
    }
   ]
  },
  { "title": "容器指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "容器 CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{addr=~\"$addr\", name=~\"$name\"}[$__rate_interval]) * 100",
     "legendFormat": "{{name}}__{{image}}"
    }
   ]
  },
  {
   "title": "容器网络流量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{addr=~\"$addr\", name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}__{{image}}_Receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{addr=~\"$addr\", name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}__{{image}}_Transmit"
    }
   ]
  },
  {
   "title": "容器内存使用量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{addr=\"$addr\", name=~\"$name\"}",
     "legendFormat": "{{name}}__{{image}}"
    }
   ]
  },
  { "title": "容器详细信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "容器详细信息",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{addr=~\"$addr\", name=~'.+'}[$__rate_interval]) * 100"
    },
    {
     "expr": "container_spec_memory_limit_bytes{addr=~\"$addr\", name=~\".+\"}"
    },
    {
     "expr": "container_memory_usage_bytes{addr=~\"$addr\", name=~\".+\"}"
    }
   ]
  }
 ]
}