{
 "title": "DNS解析视图展现",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "DNS设备",
    "query": "{\"find\":\"terms\",\"field\":\"F5hostname.keyword\"}"
   },
   {
    "name": "queryname",
    "label": "查询域名",
    "query": "{\"find\":\"terms\",\"field\":\"queryname.keyword\",\"query\":\"F5hostname.keyword:$device\"}"
   },
   {
    "name": "responename",
    "label": "响应域名",
    "query": "{\"find\":\"terms\",\"field\":\"responsename.keyword\",\"query\":\"F5hostname.keyword:$device\"}"
   },
   {
    "name": "client",
    "label": "客户端",
    "query": "{\"find\":\"terms\",\"field\":\"clientip.keyword\"}"
   },
   {
    "name": "queryid",
    "label": "查询ID",
    "query": "{\"find\":\"terms\",\"field\":\"queryid.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "解析来源地理分布",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "geoip.location", "id": "2", "settings": { "precision": "3" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "实时解析请求走势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "实时解析请求数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:viewname AND F5hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    },
    {
     "alias": "实时解析响应数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:responseflag",
     "timeField": "@timestamp"
    },
    {
     "alias": "解析失败响应数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "answer:empty",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "每线路请求数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "listenervs.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求域名TOP10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "queryname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "解析总请求数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "viewname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应状态趋势",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "responsecode.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND clientip.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "失败解析总请求数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "answer.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "answer:empty AND  F5hostname.keyword:[[device]] AND clientip.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求解析类型TOP10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "querytype.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "解析请求城市TOP10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "geoip.city_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应解析类型TOP10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "answer.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND responsename.keyword:[[responename]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应解析记录",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "recordip.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND responsename.keyword:[[responename]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "解析请求客户端TOP20",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientip.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "线路解析比例",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "listenervs.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应域名TOP10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "responsename.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND responsename.keyword:[[responename]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DNS_Request_List",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "clientip.keyword",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "listenervs.keyword",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "querytype.keyword",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "queryid.keyword",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "queryname.keyword",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "F5hostname.keyword",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "F5hostname.keyword:[[device]] AND queryname.keyword:[[queryname]] AND clientip.keyword:[[client]] AND queryid.keyword:[[queryid]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "失败解析统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "clientip.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "queryid.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "responsecode.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:emptyresponse AND F5hostname.keyword:[[device]] AND queryid.keyword:[[queryid]] AND clientip.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}