{
 "title": "F5设备状态监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(sysSystemNodeName,  job)"
    }
   },
   {
    "name": "Host_Name",
    "label": "设备名称",
    "query": {
     "query": "label_values(sysSystemNodeName)"
    }
   },
   {
    "name": "IP",
    "label": "设备IP",
    "query": {
     "query": "label_values(sysSystemNodeName{sysSystemNodeName=\"$Host_Name\"}, instance)"
    }
   },
   {
    "name": "VS_Name",
    "label": "VS名称",
    "query": {
     "query": "label_values(ltmVirtualServName{instance=\"$IP\"},ltmVirtualServName)"
    }
   },
   {
    "name": "VS_State",
    "query": {
     "query": "label_values(ltmVsStatusAvailState{ltmVsStatusName=\"$VS_Name\"},ltmVsStatusName)"
    }
   },
   {
    "name": "Persist_State",
    "query": {
     "query": "label_values(ltmVirtualServPersistUseDefault{ltmVirtualServPersistVsName=\"$VS_Name\"},ltmVirtualServPersistVsName)"
    }
   },
   {
    "name": "Rule_State",
    "query": {
     "query": "label_values(ltmVirtualServRuleRuleName{ltmVirtualServRuleVirtualServerName=\"$VS_Name\"},ltmVirtualServRuleVirtualServerName)"
    }
   },
   {
    "name": "Pool_Name",
    "label": "Pool名称",
    "query": {
     "query": "label_values(ltmPoolName{instance=\"$IP\"},ltmPoolName)"
    }
   },
   {
    "name": "Pool_State",
    "query": {
     "query": "label_values(ltmPoolStatusAvailState{ltmPoolStatusName=\"$Pool_Name\"}, ltmPoolStatusName)"
    }
   },
   {
    "name": "Pool_Member",
    "query": {
     "query": "label_values(ltmPoolMemberAddr{ltmPoolMemberPoolName=\"$Pool_Name\"}, ltmPoolMemberPoolName)"
    }
   },
   {
    "name": "Pool_Stat",
    "query": {
     "query": "label_values(ltmPoolStatServerTotConns{ltmPoolStatName=\"$Pool_Name\"}, ltmPoolStatName)"
    }
   },
   {
    "name": "Pool_MStat",
    "query": {
     "query": "label_values(ltmPoolMemberStatServerCurConns{ltmPoolMemberStatPoolName=\"$Pool_Name\"}, ltmPoolMemberStatPoolName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "硬件状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "工作状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysCmFailoverStatusStatus{instance=\"$IP\"} -0",
     "legendFormat": "{{sysCmFailoverStatusStatus}}"
    }
   ]
  },
  {
   "title": "CPU 核心使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sysMultiHostCpuUsageRatio5m{instance=\"$IP\"}",
     "legendFormat": "CPU核心：{{sysMultiHostCpuIndex}}"
    }
   ]
  },
  {
   "title": "同步状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysCmSyncStatusStatus{instance=\"$IP\"}",
     "legendFormat": "{{sysCmSyncStatusStatus}}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sysGlobalHostMemUsedKb{instance=\"$IP\"} / sysGlobalHostMemTotalKb{instance=\"$IP\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "sysGlobalHostOtherMemUsedKb{instance=\"$IP\"} / sysGlobalHostOtherMemTotalKb{instance=\"$IP\"}",
     "legendFormat": "系统"
    },
    {
     "expr": "sysTmmStatMemoryUsedKb{instance=\"$IP\"} /sysTmmStatMemoryTotalKb{instance=\"$IP\"}",
     "legendFormat": "TMM:{{sysTmmStatTmmId}}"
    }
   ]
  },
  {
   "title": "CPU 全局使用",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysGlobalHostCpuUsageRatio5s{instance=\"$IP\"}",
     "legendFormat": "{instance=\"$IP\"}"
    }
   ]
  },
  {
   "title": "TMM CPU 使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sysTmmStatTmUsageRatio5s{instance=\"$IP\"}",
     "legendFormat": "{{sysTmmStatTmmId}}"
    }
   ]
  },
  {
   "title": "开机时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$IP\"} * 10",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "接口状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "网络接口流量",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "rate(sysInterfaceStatBytesIn{instance=\"$IP\"}[5m])"
    },
    {
     "expr": "rate(sysInterfaceStatBytesOut{instance=\"$IP\"}[5m])"
    },
    {
     "expr": "delta(sysInterfaceStatBytesIn{instance=\"$IP\"}[$__range])"
    },
    {
     "expr": "delta(sysInterfaceStatBytesOut{instance=\"$IP\"}[$__range])"
    }
   ]
  },
  {
   "title": "网络接口流量总计",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(sysInterfaceStatBytesIn{instance=\"$IP\"}[5m]))",
     "legendFormat": "流入"
    },
    {
     "expr": "sum(rate(sysInterfaceStatBytesOut{instance=\"$IP\"}[5m]))",
     "legendFormat": "流出"
    }
   ]
  },
  {
   "title": "网络接口状态",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sysInterfaceStatus{instance=\"$IP\"} -0",
     "legendFormat": "{{sysInterfaceName}}"
    },
    {
     "expr": "sysInterfaceMediaActiveSpeed{instance=\"$IP\"} -0"
    },
    {
     "expr": "sysInterfaceMediaActiveDuplex{instance=\"$IP\"} -0"
    },
    {
     "expr": "sysInterfaceMacAddr{instance=\"$IP\"} -0"
    }
   ]
  },
  {
   "title": "VLAN接口实时流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(sysVlanStatBytesIn{instance=\"$IP\"}[5m])",
     "legendFormat": "流入：{{sysVlanStatVlanName}}"
    },
    {
     "expr": "rate(sysVlanStatBytesOut{instance=\"$IP\"}[5m])",
     "legendFormat": "流出：{{sysVlanStatVlanName}}"
    }
   ]
  },
  { "title": "Virtual_Server状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "VS实时状态一览",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "ltmVirtualServName{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVirtualServAddr{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVirtualServPort{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVirtualServType{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVirtualServSourceAddressTranslationType{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVirtualServSourceAddressTranslationPool{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVirtualServDefaultPool{instance=\"$IP\",ltmVirtualServName=\"$VS_Name\"} -0"
    },
    {
     "expr": "ltmVsStatusAvailState{instance=\"$IP\",ltmVsStatusName=\"$VS_State\"} -0"
    },
    {
     "expr": "ltmVirtualServPersistUseDefault{instance=\"$IP\",ltmVirtualServPersistVsName=\"$Persist_State\"} -0"
    },
    {
     "expr": "ltmVirtualServRuleRuleName{instance=\"$IP\",ltmVirtualServRuleVirtualServerName=\"$Rule_State\"} -0"
    }
   ]
  },
  {
   "title": "VS实时访问流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(ltmVirtualServStatClientBytesIn{instance=\"$IP\",ltmVirtualServStatName=\"$VS_State\"}[5m])",
     "legendFormat": "流入：{{ltmVirtualServStatName}}"
    },
    {
     "expr": "rate(ltmVirtualServStatClientBytesOut{instance=\"$IP\",ltmVirtualServStatName=\"$VS_State\"}[5m])",
     "legendFormat": "流出：{{ltmVirtualServStatName}}"
    }
   ]
  },
  {
   "title": "VS实时访问连接",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ltmVirtualServStatClientCurConns{instance=\"$IP\",ltmVirtualServStatName=\"$VS_State\"}",
     "legendFormat": "VS：{{ltmVirtualServStatName}}"
    }
   ]
  },
  { "title": "Pool&Member状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Pool实时状态一览",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "ltmPoolName{instance=\"$IP\",ltmPoolName=\"$Pool_Name\"} -0"
    },
    {
     "expr": "ltmPoolMonitorRule{instance=\"$IP\",ltmPoolName=\"$Pool_Name\"} -0"
    },
    {
     "expr": "ltmPoolMinActiveMembers{instance=\"$IP\",ltmPoolName=\"$Pool_Name\"} -0"
    },
    {
     "expr": "ltmPoolStatusAvailState{instance=\"$IP\",ltmPoolStatusName=\"$Pool_State\"} -0"
    },
    {
     "expr": "ltmPoolLbMode{instance=\"$IP\",ltmPoolName=\"$Pool_Name\"} -0"
    },
    {
     "expr": "ltmPoolMemberAddr{instance=\"$IP\",ltmPoolMemberPoolName=\"$Pool_Member\"} -0"
    },
    {
     "expr": "ltmPoolMemberMonitorState{instance=\"$IP\",ltmPoolMemberPoolName=\"$Pool_Member\"} -0"
    },
    {
     "expr": "ltmPoolMemberPriority{instance=\"$IP\",ltmPoolMemberPoolName=\"$Pool_Member\"} -0"
    }
   ]
  },
  {
   "title": "Pool实时连接&流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ltmPoolStatServerTotConns{instance=\"$IP\",ltmPoolStatName=\"$Pool_Stat\"}",
     "legendFormat": "连接：{{ltmPoolStatName}}"
    },
    {
     "expr": "rate(ltmPoolStatServerBytesIn{instance=\"$IP\",ltmPoolStatName=\"$Pool_Stat\"}[5m])",
     "legendFormat": "流入：{{ltmPoolStatName}}"
    },
    {
     "expr": "rate(ltmPoolStatServerBytesOut{instance=\"$IP\",ltmPoolStatName=\"$Pool_Stat\"}[5m])",
     "legendFormat": "流出：{{ltmPoolStatName}}"
    }
   ]
  },
  {
   "title": "PoolMember实时连接&流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ltmPoolMemberStatServerCurConns{instance=\"$IP\",ltmPoolMemberStatPoolName=\"$Pool_MStat\"}",
     "legendFormat": "连接：{{ltmPoolMemberStatNodeName}}"
    },
    {
     "expr": "rate(ltmPoolMemberStatServerBytesIn{instance=\"$IP\",ltmPoolMemberStatPoolName=\"$Pool_MStat\"}[5m])",
     "legendFormat": "流入：{{ltmPoolMemberStatNodeName}}"
    },
    {
     "expr": "rate(ltmPoolMemberStatServerBytesOut{instance=\"$IP\",ltmPoolMemberStatPoolName=\"$Pool_MStat\"}[5m])",
     "legendFormat": "流出：{{ltmPoolMemberStatNodeName}}"
    }
   ]
  }
 ]
}