{
 "title": "安全防护态势展示",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "WAF设备",
    "query": "{\"find\":\"terms\",\"field\":\"host.keyword\"}"
   },
   {
    "name": "policy",
    "label": "安全策略",
    "query": "{\"find\":\"terms\",\"field\":\"policy_name.keyword\",\"query\":\"host.keyword:$host\"}"
   },
   {
    "name": "vs",
    "label": "VS_Name",
    "query": "{\"find\":\"terms\",\"field\":\"web_application_name.keyword\",\"query\":\"policy_name.keyword:$policy\"}"
   },
   {
    "name": "client",
    "label": "攻击来源",
    "query": "{\"find\":\"terms\",\"field\":\"ip_client.keyword\"}"
   },
   {
    "name": "support_id",
    "label": "Support_ID",
    "query": "{\"find\":\"terms\",\"field\":\"support_id.keyword\",\"query\":\"host.keyword:$host\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "安全事件详情",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ip_client.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "x_forwarded_for_header_value.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "policy_name.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "attack_type.keyword",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "violations.keyword",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "sub_violations.keyword",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "安全事件详情",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "request.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "violation_rating.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "sig_ids.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "request_status.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "support_id.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "dest_ip.keyword",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "web_application_name.keyword",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "安全事件数量统计",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attack_type.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.keyword:[[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "安全事件时间曲线",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:attack_type AND host.keyword:[[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "攻击来源TOP10",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ip_client.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "攻击类型比例",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attack_type.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "攻击违规分布",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "实时防护状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "攻击违规详情",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sub_violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:[[support_id]] AND host.keyword:[[host]] AND policy_name.keyword:[[policy]] AND web_application_name.keyword:[[vs]] AND ip_client.keyword:[[client]]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}